steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-northeast1-docker.pkg.dev/oshi-high/oshi-high/image:latest', 
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-northeast1-docker.pkg.dev/oshi-high/oshi-high/image:latest'
    ]
options:
  logging: CLOUD_LOGGING_ONLY