steps:
  # 1. ビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-northeast1-docker.pkg.dev/ai-sns-app/oshi-high/oshi-app:latest', 
      '.'
    ]

  # 2. プッシュ（ここがエラーの箇所）
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-northeast1-docker.pkg.dev/ai-sns-app/oshi-high/oshi-app:latest'
    ]

options:
  logging: CLOUD_LOGGING_ONLY