-- Reset database for Prisma migration
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
DROP TABLE IF EXISTS "SupportTransaction" CASCADE;
DROP TABLE IF EXISTS "YellMaterial" CASCADE;
DROP TABLE IF EXISTS "Ad" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "VerificationToken" CASCADE;
DROP TABLE IF EXISTS "Idol" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS idols CASCADE;

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS public;
